// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhYJ-zUgG0h5zvv7h00kdaUvsB-hSgWNw',
    appId: '1:548708201155:web:b1d92592697223f7e16876',
    messagingSenderId: '548708201155',
    projectId: 'plant-companion-81d67',
    authDomain: 'plant-companion-81d67.firebaseapp.com',
    storageBucket: 'plant-companion-81d67.firebasestorage.app',
    measurementId: 'G-28DYB26F49',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8HLkbjtoJ7xOmDtXUAudCXcsvGwRprwQ',
    appId: '1:548708201155:android:ae108353e8790ef4e16876',
    messagingSenderId: '548708201155',
    projectId: 'plant-companion-81d67',
    storageBucket: 'plant-companion-81d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEpLVYW9MXkczdKc9CBPkJRF1C533madg',
    appId: '1:548708201155:ios:ab92e1793e470d76e16876',
    messagingSenderId: '548708201155',
    projectId: 'plant-companion-81d67',
    storageBucket: 'plant-companion-81d67.firebasestorage.app',
    iosClientId: '548708201155-v5enpgl9ju6agh0d3j8ehjc17r3mq731.apps.googleusercontent.com',
    iosBundleId: 'com.plantcompanion.plantCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEpLVYW9MXkczdKc9CBPkJRF1C533madg',
    appId: '1:548708201155:ios:ab92e1793e470d76e16876',
    messagingSenderId: '548708201155',
    projectId: 'plant-companion-81d67',
    storageBucket: 'plant-companion-81d67.firebasestorage.app',
    iosClientId: '548708201155-v5enpgl9ju6agh0d3j8ehjc17r3mq731.apps.googleusercontent.com',
    iosBundleId: 'com.plantcompanion.plantCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhYJ-zUgG0h5zvv7h00kdaUvsB-hSgWNw',
    appId: '1:548708201155:web:8dfddae71c19162ee16876',
    messagingSenderId: '548708201155',
    projectId: 'plant-companion-81d67',
    authDomain: 'plant-companion-81d67.firebaseapp.com',
    storageBucket: 'plant-companion-81d67.firebasestorage.app',
    measurementId: 'G-Z2690K7LCF',
  );
}
