import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:provider/provider.dart';
import 'app_state.dart';
import 'theme/app_theme.dart';
import 'firebase_options.dart'; // Generated by `flutterfire configure` — see README

import 'screens/welcome_screen.dart';
import 'screens/permissions_screen.dart';
import 'screens/sign_in_screen.dart';
import 'screens/home_screen.dart';
import 'screens/add_plant_screen.dart';
import 'screens/manual_add_screen.dart';
import 'screens/plant_detail_screen.dart';
import 'screens/diagnose_screen.dart';
import 'screens/diagnosis_result_screen.dart';
import 'screens/paywall_screen.dart';
import 'screens/settings_screen.dart';
import 'screens/settings_subscreens.dart';
import 'screens/guest_gate_screen.dart';
import 'screens/calculators_screen.dart';
import 'screens/growth_journey_screen.dart';
import 'screens/wishlist_plant_detail_screen.dart';
import 'screens/reminders_screen.dart';
import 'screens/my_plants_screen.dart';
import 'screens/splash_screen.dart';
import 'services/notification_service.dart';
import 'services/push_notification_service.dart';
import 'widgets/custom_bottom_nav.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await NotificationService.instance.init();
  // Server-sent announcements/feature call-outs — separate system from the
  // local watering reminders above (see PushNotificationService's own
  // docstring). Initialized unconditionally at startup, same as
  // NotificationService, since receiving these isn't tied to the
  // reminders_enabled preference at all.
  await PushNotificationService.instance.init();
  // No purchase SDK to configure here — VANYA sells subscriptions on the
  // website (vanya-web/), not inside this app. See
  // backend/app/services/billing_service.py's module docstring for why
  // (Google Play's 0%-commission "reader app" exemption requires the app
  // to have zero in-app purchase UI at all) and screens/paywall_screen.dart,
  // which is informational only.

  final appState = AppState();
  await appState.bootstrap();

  runApp(
    ChangeNotifierProvider.value(
      value: appState,
      child: const PlantCompanionApp(),
    ),
  );
}

class PlantCompanionApp extends StatefulWidget {
  const PlantCompanionApp({super.key});

  @override
  State<PlantCompanionApp> createState() => _PlantCompanionAppState();
}

class _PlantCompanionAppState extends State<PlantCompanionApp> with WidgetsBindingObserver {
  // AppState.bootstrap() already resolved the real starting screen (welcome
  // vs home) before runApp() was called — the splash is purely a
  // presentation gate shown once on top of that, not part of AppState's own
  // routing, so it doesn't need to know or care which screen is under it.
  //
  // Seeded from AppState.hasSeenIntro, which is in-memory only (not
  // disk-backed) on purpose — see that field's own docstring: the intro
  // is meant to replay on every genuine fresh process start (a real
  // close-and-reopen), which is exactly what a fresh in-memory default
  // gives here, at the accepted cost of also occasionally replaying after
  // plain backgrounding if Android happens to reclaim the process in
  // between (indistinguishable from a real close at this level).
  late bool _showSplash = !context.read<AppState>().hasSeenIntro;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    // Catches "left the app to pay on vanya.app in the browser, came
    // back" — there's no in-app purchase event to hook anymore (see
    // paywall_screen.dart), so this is how a just-completed web
    // subscription actually shows up without the user having to
    // manually pull-to-refresh anywhere.
    if (state == AppLifecycleState.resumed) {
      context.read<AppState>().handleAppResumed();
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'VANYA',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      darkTheme: AppTheme.dark,
      // Real implementation note: Settings screen's Dark Mode toggle
      // (still to be built) should set ThemeMode.light/.dark explicitly via
      // a value on AppState, rather than following the OS setting — same
      // as the React version's own toggle rather than a system preference.
      themeMode: ThemeMode.system,
      home: _showSplash
          ? SplashScreen(
              onDone: () {
                context.read<AppState>().markIntroSeen();
                setState(() => _showSplash = false);
              },
            )
          : const RootRouter(),
    );
  }
}

/// Mirrors App.jsx's big conditional-render block — reads AppState.screen
/// and shows the matching screen widget. Each screen is a StatefulWidget
/// or StatelessWidget that reads/calls into the shared AppState via
/// Provider, the same way React screens received props/callbacks from
/// App.jsx.
class RootRouter extends StatelessWidget {
  const RootRouter({super.key});

  @override
  Widget build(BuildContext context) {
    final appState = context.watch<AppState>();

    // Home / My Plants / Reminders share one persistent bottom-nav shell —
    // everything else (detail views, flows, settings) is a normal
    // full-screen destination with its own Scaffold/back button, same as
    // before. Scan has no tab body of its own; it's a shortcut to addPlant.
    final Widget child = AppState.tabScreens.contains(appState.screen)
        ? _TabShell(screen: appState.screen)
        : _screenFor(appState);

    // BUGID-S002: no screen swap here goes through a real Navigator route,
    // so the system back button/edge-swipe gesture previously had nothing
    // to intercept and fell straight through to closing the app. Reroute it
    // into AppState.goBack() — the same "back" every on-screen Back button
    // already uses — and only let the system actually pop (exit the app)
    // once there's genuinely nowhere left to go.
    return PopScope(
      canPop: !appState.canGoBack,
      onPopInvokedWithResult: (didPop, _) {
        if (didPop) return;
        appState.goBack();
      },
      child: child,
    );
  }

  Widget _screenFor(AppState appState) {
    switch (appState.screen) {
      case 'welcome':
        return const WelcomeScreen();
      case 'permissions':
        return const PermissionsScreen();
      case 'signin':
        return const SignInScreen();
      case 'addPlant':
        return const AddPlantScreen();
      case 'manualAdd':
        return const ManualAddScreen();
      case 'plantDetail':
        return const PlantDetailScreen();
      case 'diagnose':
        return const DiagnoseScreen();
      case 'diagnosisResult':
        return const DiagnosisResultScreen();
      case 'plantFacts':
        return const PlantFactsScreen();
      case 'paywall':
        return const PaywallScreen();
      // 'settings' is no longer handled here -- it's a tab-shell screen
      // now (see AppState.tabScreens/_TabShell above), so RootRouter.build
      // routes it there before this switch is ever consulted.
      case 'plan':
        return const PlanScreen();
      case 'notifications':
        return const NotificationSettingsScreen();
      case 'camera':
        return const CameraSettingsScreen();
      case 'guestGate':
        return const GuestGateScreen();
      case 'calculators':
        return const CalculatorsScreen();
      case 'growthJourney':
        return const GrowthJourneyScreen();
      case 'wishlistPlantDetail':
        return const WishlistPlantDetailScreen();
      default:
        return const _TabShell(screen: 'home');
    }
  }
}

/// Shared Scaffold + floating bottom nav for the four top-level tabs.
/// Home/MyPlantsScreen/RemindersScreen/SettingsScreen render only their
/// body content (no own Scaffold/AppBar) so they slot into this shell
/// cleanly.
class _TabShell extends StatelessWidget {
  final String screen;
  const _TabShell({required this.screen});

  @override
  Widget build(BuildContext context) {
    final appState = context.read<AppState>();
    final Widget body = switch (screen) {
      'myPlants' => const MyPlantsScreen(),
      'reminders' => const RemindersScreen(),
      'settings' => const SettingsScreen(),
      _ => const HomeScreen(),
    };

    return Scaffold(
      backgroundColor: AppColors.bgOf(context),
      extendBody: true,
      body: SafeArea(bottom: false, child: body),
      bottomNavigationBar: CustomBottomNav(
        current: screen,
        onHome: () => appState.goTo('home'),
        onMyPlants: () => appState.goTo('myPlants'),
        onScan: () => appState.goTo('addPlant'),
        onReminders: () => appState.goTo('reminders'),
        onSettings: () => appState.goTo('settings'),
      ),
    );
  }
}
